# -*- coding: utf-8 -*-
"""CNN_Crop_Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Ou8rnud9BPV7nxAyz1Bc9jBXIp9m9JR
"""

!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

link = "https://drive.google.com/open?id=19o84Ph019PjY5TRMVWQrWqY5xiSI7iSN"

fluff, id = link.split('=')

import pandas as pd
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('dataset2.csv')  
df = pd.read_csv('dataset2.csv')

df.head()

output = '0.2189'
Y = df[output].values
print(Y)
print(len(Y))

df = df.drop(output,1)
print(df.head)

X = df.values
print(X)
print(len(X))

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

X_train[0].shape

X_train = X_train.reshape(779,240,150,3)
X_test = X_test.reshape(195,240,150,3)

X_train = X_train/255
X_test = X_test/255

from keras.utils import to_categorical
print(Y_train[0])
Y_train = to_categorical(Y_train)
Y_test = to_categorical(Y_test)
Y_train[0]

print(Y_train)

from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten,MaxPooling2D,Dropout
model = Sequential()
model.add(Conv2D(240, kernel_size=5, activation='relu', input_shape=(240,150,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(120, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(120, activation='relu'))
model.add(Dense(60, activation='relu'))
model.add(Dense(5, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=20)

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/'My Drive/'/FarmFrenzi

model.save('CNN.h5')