# -*- coding: utf-8 -*-
"""SIHPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B9_uPyvvfkVwhEtyToMbOAqgLCO5_IB7
"""

from keras.models import load_model
import pandas as pd
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
# import pickle
import cv2
# from google.colab.patches import cv2_imshow

def work():
    # from google.colab import drive
    # drive.mount('/content/drive')

    model = load_model("./CNN.h5")


    img = cv2.imread('./test_image.jpg', cv2.IMREAD_UNCHANGED)
    # print(img.shape)
    width = 240
    height = 150
    img = cv2.resize(img, (width, height), interpolation = cv2.INTER_NEAREST) 

    # print(img.shape)
    #cv2.rectangle(img, (128, 128), (163, 172), (0, 450, 0, 620), 3)
    # cv2_imshow(img)

    # from matplotlib import pyplot as plt
    # from matplotlib.patches import Rectangle

    weights=model.get_weights()

    img = np.reshape(img,(1,240,150,3))
    y_pred = model.predict(img,batch_size = 200,verbose = 2,steps = None) 
    # y_pred

    # print(y_pred)

    dic= {
        0:'Coffee',
        1:'bottle gourd',
        2:'cotton',
        3:'wheat',
        4:'sugarcane'
    }

    index = np.argmax(y_pred,axis=None,out=None)

    # print(dic[index])
    return dic[index]